name: Feature request
description: Create a feature request
title: "[feat]: "
labels: enhancement
body:
    - type: textarea
      id: feature-description
      attributes:
          label: Feature description
          description: Tell us about your feature request
          placeholder: "I think this feature would be great because..."
      validations:
          required: true

    - type: textarea
      id: user-scenario
      attributes:
          label: User scenario / Use case
          description: Describe how users would use this feature
          placeholder: "As a user, I want to... so that I can..."
      validations:
          required: true

    - type: dropdown
      id: priority
      attributes:
          label: Priority
          description: How important is this feature to you?
          options:
              - Critical (blocking my usage)
              - High (significantly impacts my experience)
              - Medium (would improve my experience)
              - Low (nice to have)
      validations:
          required: true

    - type: textarea
      id: context
      attributes:
          label: Additional Context
          description: Add any other context about the feature here.
          placeholder: ex. screenshots, Stack Overflow links, forum links, etc.
      validations:
          required: false

    - type: textarea
      id: alternatives
      attributes:
          label: Alternatives considered
          description: Have you considered any alternative solutions or workarounds?
      validations:
          required: false
