name: Build and push a Docker image

on:
    push:
        branches: ["main"]
        tags: ["v*.*.*"]
    pull_request:
        branches: ["main"]
    workflow_dispatch:

env:
    # Use docker.io for Docker Hub if empty
    REGISTRY: ghcr.io
    # github.repository as <account>/<repo>
    #IMAGE_NAME: ${{ github.repository }}
    NODE_VERSION: 18

jobs:
    lint-test-build:
        name: Lint, Test and Build
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              
            - name: Setup Node.js ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: 'npm'
                  
            - name: Install dependencies
              run: npm ci
              
            - name: Lint
              run: npm run lint
              
            - name: Type check
              run: npm run typecheck
              
            - name: Build
              run: npm run build
              
            # Uncomment when tests are added
            # - name: Test
            #   run: npm test

    build-docker:
        name: Build and push Docker image
        needs: lint-test-build
        if: github.event_name != 'pull_request'
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            # This is used to complete the identity challenge
            # with sigstore/fulcio when running outside of PRs.
            id-token: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
              with:
                  platforms: "arm64,amd64"

            # Workaround: https://github.com/docker/build-push-action/issues/461
            - name: Setup Docker buildx
              uses: docker/setup-buildx-action@v2

            # Login against a Docker registry except on PR
            # https://github.com/docker/login-action
            - name: Log into registry ${{ env.REGISTRY }}
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            # Extract metadata (tags, labels) for Docker
            # https://github.com/docker/metadata-action
            - name: Extract Docker metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  images: ${{ env.REGISTRY }}/${{ github.repository }}
                  tags: |
                      type=raw,value=latest,enable={{is_default_branch}}
                      type=semver,pattern=v{{version}}
                      type=semver,pattern=v{{major}}.{{minor}}
                      type=semver,pattern=v{{major}}

            # Build and push Docker image with Buildx (don't push on PR)
            # https://github.com/docker/build-push-action
            - name: Build and push Docker image
              id: build-and-push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  build-args: VERSION=${{github.ref_name}}
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  platforms: linux/amd64,linux/arm64
                  labels: ${{ steps.meta.outputs.labels }}
